# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Renderizer < Formula
  desc "CLI to render Go template text files based on command line parameters and/or a YAML"
  homepage "https://github.com/gomatic/renderizer"
  version "2.0.12"
  license "GPL-3.0"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/gomatic/renderizer/releases/download/v2.0.12/renderizer_darwin_x86_64.tar.gz"
    sha256 "cd0552845346724ec287f6919cc17f1e50682437b1935dfd7ac2251b17a052ac"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/gomatic/renderizer/releases/download/v2.0.12/renderizer_linux_x86_64.tar.gz"
    sha256 "768378aa9163c19b8bdb058cca015742a9738f2023e0a987cd3a837beaf3a348"
  end

  def install
    bin.install "renderizer"
  end
end
